"""empty message

Revision ID: 412fc431f6fd
Revises: 217993b14e97
Create Date: 2020-08-04 10:35:09.074725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412fc431f6fd'
down_revision = '217993b14e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
